services:
  db:
    image: postgres:16
    container_name: trello_postgres
    environment:
      POSTGRES_DB: trello
      POSTGRES_USER: trello
      POSTGRES_PASSWORD: trello123
    ports:
      - "5432:5432"
    volumes:
      - trello_pgdata:/var/lib/postgresql/data

volumes:
  trello_pgdata: {}